### ISSUE TITLE
Create team session

### ISSUE THREAD

**Issue by simoneas02** [womenwhocoderecife/womendevprojects#5]
The web page should show the team session with a photo, name and brief description of each person who is part of the team.

<img width="1343" alt="screen shot 2018-07-24 at 17 08 35" src="https://user-images.githubusercontent.com/7841344/43163760-7bac6ab6-8f65-11e8-9300-bc5fb6608f64.png">

**Comment by wwcoderecife** [comment]
ok

**Comment by karinamachado** [comment]
ok

**Comment by karinamachado** [comment]
Commit the issue Team Section, so, need to fix to responsive, testing at the browser - Device toolbar. @simoneas02, please look what flexbox properties to solve this problems. Thanks.

<img width="843" alt="screen shot 2018-07-29 at 00 36 38" src="https://user-images.githubusercontent.com/6514093/43362750-3179e8e0-92c8-11e8-9e76-b8062a9b02dd.png">
